### ISSUE TITLE
Installation 1.3.7 within pyjoulescope_ui failed

### ISSUE THREAD

**Issue by satirebird** [jetperch/joulescope_driver#6]
Installing the driver fails when installed with:

```
git clone https://github.com/jetperch/pyjoulescope_ui.git
cd pyjoulescope_ui
python3.10 -m venv .venv
source .venv/bin/activate
pip install -U -r requirements.txt
```

Reported Error:
```
Collecting pyjoulescope_driver<2.0.0,>=1.3.7
  Downloading pyjoulescope_driver-1.3.7.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 12.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/sven/install/joulescope/pyjoulescope_ui2/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/sven/install/joulescope/pyjoulescope_ui2/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/sven/install/joulescope/pyjoulescope_ui2/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jouiabvd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-jouiabvd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jouiabvd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      ModuleNotFoundError: No module named 'pyjoulescope_driver'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

System: Ubuntu 22.04

**Comment by mliberty1** [comment]
Hi @satirebird and thanks for reporting this issue.  I confirm that `python3 -m pip install pyjoulescope_driver` gives the same error with a clean venv on Ubuntu 22.04 LTS.  That error is entirely unhelpful, so I will have to investigate.  Python packaging recently obsoleted the python setup.py` method, so I suspect that this is related.

In the meantime, here is a process to build and install from source:

```
python3 -m venv ~/venv/tmp
. ~/venv/tmp/bin/activate
pip3 install Cython numpy requests setuptools wheel
cd {path/to}/joulescope_driver
python3 setup.py bdist_wheel
pip3 install dist/pyjoulescope_driver*
```

Same as [this issue](https://github.com/jetperch/pyjoulescope_ui/issues/184):

**Comment by mliberty1** [comment]
Fixed in 1.3.9.
